### ISSUE TITLE
DLL not included in package on Our

### ISSUE THREAD

**Issue by enkelmedia** [KevinJump/Our.Umbraco.StyledEditors#1]
Hi!

Just wanted to try out the package, as far as i understand the datatypes are created from code and not configured in the package.manifest right? 

I did not find any dll in the our-package - not sure if I'm doing something wrong or if its just missing?

Cheers!

**Comment by KevinJump** [comment]
Indeed you're right! - I missed that one when I created the package (doh!) 

Updated package on our now.
